### ISSUE TITLE
screenshots please

### ISSUE THREAD

**Issue by johnfelipe** [devinlynch/ParliamentClient#1] opened 2015-03-27 02:37 UTC
Screenshots please

**Comment by devinlynch** [comment] 2015-03-27 03:08
Hi Felipe, this is a school project and in the early stages.  I will post some screenshots once it is complete.

**Comment by JohnMarsh** [comment] 2015-03-27 03:13
Could not reproduce. Closing Issue.

**Closed by JohnMarsh** 2015-03-27 03:13 UTC
